

services:
  api:
    build: .
    container_name: sabia-api

    restart: always
    depends_on:
      - mysql-sabia
    ports:
      - "3000:3000"
    env_file:
      - .env
    volumes:
      - /var/docker/sabia-api/storage:/app/storage

